autoscaling:
  enabled: true
  maxReplicas: 6
  minReplicas: 3
environment: production
image:
  pullPolicy: Always
  tag: latest
replicaCount: 3
resources:
  limits:
    cpu: 5135m
    memory: 1393Mi
  requests:
    cpu: 2567m
    memory: 1072Mi
