environment: production

replicaCount: 3

image:
    tag: "latest"
    pullPolicy: Always

resources:
    limits:
    cpu: 5625m  
    memory: 2197Mi
    requests:
    cpu: 2812m
    memory: 1690Mi

autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 6 
