
    ```
    environment: production

    replicaCount: 3

    image:
    repository: polinux/stress-ng
    tag: "latest"
    pullPolicy: IfNotPresent

    resources:
    limits:
        cpu: 5625m  
        memory: 2197Mi
    requests:
        cpu: 2812m
        memory: 1690Mi

    autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 6 
    ```
    
