autoscaling:
  enabled: true
  maxReplicas: 6
  minReplicas: 3
environment: production
image:
  pullPolicy: Always
  tag: latest
replicaCount: 3
resources:
  limits:
    cpu: 5091m
    memory: 2361Mi
  requests:
    cpu: 2545m
    memory: 1816Mi
